services:
  certify-nft-api3:
    container_name: certify-nft-api3
    image: certify-nft-api3:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4002:4002"
    restart: always
    networks:
      - certify-nft-network
    volumes:
      - .env:/app/.env
      - /home/gpadaka19/uploads:/app/uploads

networks:
  certify-nft-network:
    external: true 