version: '3.8'
services:
  app:
    build: .
    ports:
      - "4002:4002"
    restart: always
    networks:
      - certify-nft-network
    volumes:
      - .env:/app/.env
      - ./uploads:/app/uploads

networks:
  certify-nft-network:
    external: true 